import { BookMarked, Castle, Flame, MapPinned, PawPrint, Scroll, Search, ShieldAlert, Skull, Sparkles, Users } from 'lucide-react'
import { useMemo, useState } from 'react'
import type { DiscoveryDisposition, GameState } from '../types/game'

interface Props { state: GameState }
type ArchiveTab = 'chronicle' | 'discoveries' | 'places' | 'bestiary' | 'people' | 'consequences'

const categoryIcons = { guild: Castle, expedition: Scroll, world: Flame, character: Skull, discovery: Sparkles }
const dispositionLabels: Record<DiscoveryDisposition, string> = { unreviewed: 'ждёт решения', published: 'опубликовано', archived: 'в архиве', sold: 'продано', secret: 'засекречено' }
const archiveTabs: Array<[ArchiveTab, string, typeof BookMarked]> = [
  ['chronicle', 'Хроника', BookMarked], ['discoveries', 'Открытия', Sparkles], ['places', 'Места', MapPinned], ['bestiary', 'Бестиарий', PawPrint], ['people', 'Люди', Users], ['consequences', 'Последствия', ShieldAlert],
]

export default function ArchiveView({ state }: Props) {
  const [query, setQuery] = useState('')
  const [category, setCategory] = useState('all')
  const [tab, setTab] = useState<ArchiveTab>('chronicle')
  const entries = useMemo(() => [...state.chronicle].filter((entry) => (category === 'all' || entry.category === category) && `${entry.title} ${entry.text}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => b.year - a.year || b.day - a.day), [state.chronicle, query, category])
  const discoveries = useMemo(() => [...state.discoveries].filter((discovery) => `${discovery.title} ${discovery.summary}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => b.createdYear - a.createdYear || b.createdDay - a.createdDay), [state.discoveries, query])
  const knownSites = state.world.sites.filter((site) => site.state !== 'unknown' && `${site.name} ${site.origin} ${site.layers.join(' ')}`.toLowerCase().includes(query.toLowerCase()))
  const rememberedPeople = state.characters.filter((character) => (character.status === 'dead' || character.status === 'missing' || character.status === 'retired' || character.careerStage === 'legend') && `${character.name} ${character.profession} ${character.ancestry}`.toLowerCase().includes(query.toLowerCase()))
  const bestiary = state.bestiary.filter((entry) => { const species = state.world.monsterSpecies.find((candidate) => candidate.id === entry.speciesId); return `${species?.name ?? ''} ${entry.notes.join(' ')}`.toLowerCase().includes(query.toLowerCase()) }).sort((a, b) => b.knowledge - a.knowledge)
  const consequences = [...state.consequences].filter((consequence) => `${consequence.title} ${consequence.text}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => (a.status === b.status ? b.dueTick - a.dueTick : a.status === 'pending' ? -1 : 1))

  return <section className="view archive-view compact-archive-view">
    <header className="view-heading compact-heading"><div><p className="eyebrow">Память организации</p><h1>Архив</h1></div><div className="archive-summary-inline"><span><BookMarked />{state.chronicle.length}</span><span><Sparkles />{state.discoveries.length}</span><span><Skull />{state.characters.filter((character) => character.status === 'dead' || character.status === 'missing').length}</span><span><PawPrint />{state.bestiary.length}</span><span><ShieldAlert />{state.consequences.filter((consequence) => consequence.status === 'pending').length}</span></div></header>

    <div className="archive-tabs paper-card desktop-archive-tabs">{archiveTabs.map(([id, label, Icon]) => <button className={tab === id ? 'active' : ''} key={id} onClick={() => setTab(id)}><Icon size={15} />{label}</button>)}</div>
    <label className="mobile-tab-select archive-mobile-tab"><select value={tab} onChange={(event) => setTab(event.target.value as ArchiveTab)}>{archiveTabs.map(([id, label]) => <option value={id} key={id}>{label}</option>)}</select></label>

    <div className="toolbar paper-card archive-toolbar">
      <label className="search-box"><Search size={15} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Поиск" /></label>
      {tab === 'chronicle' && <select value={category} onChange={(event) => setCategory(event.target.value)}><option value="all">Все категории</option><option value="guild">Гильдия</option><option value="expedition">Экспедиции</option><option value="discovery">Открытия</option><option value="world">Мир</option><option value="character">Персонажи</option></select>}
    </div>

    {tab === 'chronicle' && <div className="archive-layout compact-archive-layout"><div className="chronicle-list compact-chronicle-list">{entries.map((entry) => { const Icon = categoryIcons[entry.category]; return <article className={`chronicle-entry compact-chronicle-entry importance-${entry.importance}`} key={entry.id}><div className="chronicle-icon"><Icon size={15} /></div><div className="chronicle-main"><div className="chronicle-title-line"><h3>{entry.title}</h3><span>{entry.year}.{entry.day}</span></div><p>{entry.text}</p></div></article> })}</div><details className="paper-card ancient-history compact-ancient-history"><summary>История региона · {state.world.history.length}</summary>{state.world.history.map((event) => <div className="history-entry" key={event.id}><span>{event.year}</span><div><h3>{event.title}</h3><p>{event.description}</p></div></div>)}</details></div>}

    {tab === 'discoveries' && <div className="archive-card-grid compact-archive-grid">{discoveries.length === 0 ? <div className="empty-state paper-card"><Sparkles /><h3>Открытий нет</h3></div> : discoveries.map((discovery) => { const lead = state.characters.find((character) => character.id === discovery.leadDiscovererId); const expedition = state.expeditions.find((candidate) => candidate.id === discovery.expeditionId); const officialReport = expedition?.reports.find((report) => report.id === expedition.officialReportId); return <article className={`paper-card discovery-record compact-archive-card disposition-${discovery.disposition}`} key={discovery.id}><div className="archive-card-title"><span className="type-chip">{discovery.type}</span><h3>{discovery.title}</h3><em>{dispositionLabels[discovery.disposition]}</em></div><div className="archive-inline-meta"><span>доказ. <b>{discovery.evidenceQuality}%</b></span><span>цена <b>{discovery.value}</b></span><span>автор <b>{lead?.name ?? '—'}</b></span><span>послед. <b>{discovery.consequenceIds.length}</b></span></div><details className="compact-details"><summary>Описание</summary><p>{discovery.summary}</p><small>Источник: {expedition?.name ?? 'неизвестен'}</small>{officialReport && <div className="official-report-line"><Scroll size={13} /><span><strong>{officialReport.title}</strong><small>{officialReport.claim}</small></span></div>}</details></article> })}</div>}

    {tab === 'places' && <div className="archive-card-grid compact-archive-grid">{knownSites.map((site) => { const tile = state.world.tiles.find((candidate) => candidate.id === site.tileId); return <article className="paper-card site-record compact-archive-card" key={site.id}><div className="archive-card-title"><span className="type-chip">{site.type}</span><h3>{site.name}</h3><em>{site.state}</em></div><div className="archive-inline-meta"><span>опасн. <b>{site.danger}/10</b></span><span>глуб. <b>{site.depth}</b></span><span>клетка <b>{tile?.x}:{tile?.y}</b></span><span>слои <b>{site.layers.length}</b></span></div><details className="compact-details"><summary>Сведения</summary><p>{site.origin}</p><div className="site-layer-list">{site.layers.map((layer) => <span key={layer}>{layer}</span>)}</div>{site.state === 'surveyed' || site.state === 'cleared' ? <p>{site.truth}</p> : <p className="muted">История ещё не подтверждена.</p>}</details></article> })}</div>}

    {tab === 'bestiary' && <div className="archive-card-grid compact-archive-grid bestiary-grid">{bestiary.length === 0 ? <div className="empty-state paper-card"><PawPrint /><h3>Бестиарий пуст</h3></div> : bestiary.map((entry) => { const species = state.world.monsterSpecies.find((candidate) => candidate.id === entry.speciesId); const legendary = state.world.monsterPopulations.filter((population) => population.speciesId === entry.speciesId && population.legendary); return <article className="paper-card bestiary-record compact-archive-card" key={entry.speciesId}><div className="archive-card-title"><span className="type-chip">{species?.origin ?? 'unknown'}</span><h3>{species?.name ?? entry.speciesId}</h3><em>{entry.knowledge}%</em></div><div className="archive-inline-meta"><span>встречи <b>{entry.encounters}</b></span><span>победы <b>{entry.victories}</b></span><span>убито <b>{entry.kills}</b></span><span>потери <b>{entry.deathsCaused}</b></span></div><div className="bestiary-meter"><span style={{ width: `${entry.knowledge}%` }} /></div><details className="compact-details"><summary>Поведение и слабости</summary><p>{species?.behavior}</p><p><b>Способности:</b> {species?.abilities.join(', ')}</p><p><b>Трофей:</b> {species?.trophy}</p><p><b>Слабость:</b> {entry.discoveredWeakness ? species?.weakness : 'неизвестна'}</p>{legendary.length > 0 && <div className="legendary-list">{legendary.map((population) => <span key={population.id}>★ {population.legendaryName}</span>)}</div>}</details></article> })}</div>}

    {tab === 'people' && <div className="archive-card-grid compact-archive-grid people-archive-grid">{rememberedPeople.length === 0 ? <div className="empty-state paper-card"><Users /><h3>Исторических фигур нет</h3></div> : rememberedPeople.map((character) => <article className={`paper-card remembered-person compact-archive-card status-${character.status}`} key={character.id}><div className="archive-card-title"><span className="type-chip">{character.careerStage}</span><h3>{character.name}</h3><em>{character.status}</em></div><div className="archive-inline-meta"><span>{character.ancestry}</span><span>{character.profession}</span><span>походы <b>{character.expeditions}</b></span><span>слава <b>{character.fame}</b></span></div>{character.memories.at(-1) && <details className="compact-details"><summary>Последняя память</summary><p>{character.memories.at(-1)!.title}: {character.memories.at(-1)!.description}</p></details>}</article>)}</div>}

    {tab === 'consequences' && <div className="consequence-timeline compact-consequence-list">{consequences.length === 0 ? <div className="empty-state paper-card"><ShieldAlert /><h3>Последствий нет</h3></div> : consequences.map((consequence) => { const discovery = state.discoveries.find((entry) => entry.id === consequence.discoveryId); return <article className={`paper-card consequence-card compact-consequence-card ${consequence.status}`} key={consequence.id}><div className="archive-card-title"><span className="type-chip">{consequence.status === 'pending' ? 'ожидается' : 'произошло'}</span><h3>{consequence.title}</h3><em>сила {consequence.magnitude}</em></div><details className="compact-details"><summary>Описание</summary><p>{consequence.text}</p><small>Источник: {discovery?.title ?? 'неизвестно'}</small></details></article> })}</div>}
  </section>
}
